---
title: "Childhood Family Structure and Early Family Formation in East and West Germany"
title-block-banner: true
toc: false
type: "Article"
author:
  - name: "<strong>Marcel Raab</strong>"
    orcid: 0000-0002-3097-1591
    email: marcel.raab@ifb.uni-bamberg.de
year: "2017"
date: "2017"
date-format: "YYYY"
publication: "Journal of Marriage and Family"
doi: "10.1111/jomf.12333"
categories:
  - Article
bibliography: raab2017.bib
csl: ../apa.csl
nocite: | 
  @raab2017

---


## Abstract

This study investigated the association between childhood living arrangements and early family formation in Germany. Drawing on persisting sociocultural differences between East and West Germany, the author examined whether the association of childhood family structure and the transition to adulthood varies in different societal contexts. Data from the German Family Panel showed that children from nontraditional family structures experience important demographic transitions faster than children who were raised by both biological parents. The study revealed considerable context‐specific differences that point to the long‐term consequences of the postwar separation of East and West Germany. Family structure was less predictive for early family formation in the postcommunist East. In addition, this study adds to a growing body of literature indicating that even seemingly similar family‐structure effects might bear very different implications—for example, for status attainment and the reproduction of inequality—depending on the sociocultural context.

::: {.callout-note}
## Citation

::: {#refs}
:::

:::



```{=html}
<style>
    section {
        background: white;
        color: black;
        border-radius: 1em;
        padding: 1em;
        left: 50% }
    #inner {
        display: inline-block;
        display: flex;
        align-items: center;
        justify-content: center }
  </style>
  <section>
    <div id="inner">
      <script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
        <span style="float:left"; 
          class="__dimensions_badge_embed__" 
          data-doi="10.1111/jomf.12333" 
          data-hide-zero-citations="true" 
          data-legend="always">
        </span>
      <script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
        <div  style="float:right"; 
          data-link-target="_blank" 
          data-badge-details="right" 
          data-badge-type="medium-donut"
          data-doi="10.1111/jomf.12333"   
          data-condensed="true" 
          data-hide-no-mentions="true" 
          class="altmetric-embed">
        </div>
    </div>
  </section>
  
```

